name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java JDK
        uses: actions/setup-java@v5.6.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: ./gradlew build

      - name: Build Docker image
        run: docker build -t nexus-pay .
